version: "3"

services:
  db:
    image: postgres:13
    restart: always
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    env_file: ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    command: bundle exec rails s -p 8000 -b '0.0.0.0'

  front:
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - HOST=0.0.0.0
    command: yarn dev

  nginx:
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: dev_stage
    env_file: ./.env
    volumes:
      - ./nginx/conf/local.conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    depends_on:
      - front
      - api

volumes:
  pgdata:
